headlines = [
"Angelina Jolie stuns at event with look-alike daughter", 
"Triple j star Bryce Mills quits after mental health break", 
"Netflix star Noah Schnapp ‘kicked out of a club’ after being ‘aggressive’", 
"Weather New South Wales, South Australia and Victoria: Huge swells, frosty Monday morning", 
"Cubitt’s Granny Flats collapses into liquidation owing $5.7m", 
"‘Keep the Sheep’: 56,000 members of Australia’s farming community revolt against live export ban", 
"John Farnham resurfaces for son’s wedding", 
"Sad reason you pay $20 for a pint", 
"‘That’s it’: Taylor Swift’s big on-stage announcement", 
"‘Not looking quite so crash hot’: The Princess of Wales pictures can’t hide royal disaster", 
"Greece finds ‘unique’ Minoan hilltop complex near new Crete airport", 
"Harry photo no one thought possible", 
"Prince Louis steals the show with Buckingham Palace balcony dance", 
"Kate makes first public appearance", 
"Suzuki Swift review: price, specifications, driving impressions", 
"Holly Valance hosts fundraiser for Donald Trump after labelling Australia ‘too woke’", 
"Prince William rules out being by Kate Middleton’s side for her comeback", 
"Mind-blowing detail revealed in Kate Middleton’s return to the spotlight", 
"Aussie warns of $45k Tesla mistake", 
"Photo of Kate, Princess of Wales, set to make history", 
"Aussie influencer speaks on wedding leaks", 
"Weather Australia: Wet and wild weekend forecast for east coast", 
"‘We’re owed an apology for vaccine mandates’", 
"Aussies rush to ATMs to withdraw cash in Cash is King campaign against card payments", 
"‘World’s hottest’ scientist Rosie Moore reveals dengue fever diagnosis", 
"More Victorian farms shut down with bird flu", 
"Uber driver’s sickening act to 80yo pensioner", 
"‘Can’t spend $7 on a donut’: Rising cost-of-living takes a bite out of hipster ‘fad’", 
"Bridgerton stars reveal fallout from show’s steamiest sex scene", 
"Jackie ‘O’ Henderson reveals why she was crying in paparazzi photos taken at a cafe", 
"Bianca Censori steps out with Kanye West wearing G-string leotard", 
"Melbourne forecast: City set to shiver through its coldest day in five years", 
"135-year-old pub falls into liquidation", 
"Aussie star’s daughter lands huge Disney role", 
"Secret Bible text changes everything", 
"Major change to Uber in Australia", 
"‘Multibillion-dollar failure’: Aussie doctors rip into Covid response", 
"Oprah Winfrey rushed to hospital, friend reveals ‘very serious’ illness", 
"‘5.5 million bags’: Calls to decriminalise cocaine in Australia as usage soars", 
"Weather: Bureau of Meteorology issues severe weather warning as wind gusts hit NSW, Victoria", 
"CBA cuts daily cash deposit limit", 
"Kevin Spacey breaks down as he reveals he’s broke", 
"A kangaroo brawl was caught on camera at a QLD campground", 
"Dog runs 6km to find help after owner drives over cliff in US", 
"Why Gen X is getting cancer more often than their parents’ generation", 
"Prince William photos confirm Prince Harry’s worst nightmare", 
"Popular brewery to shut after 36 years", 
"Kate Middleton issues rare message after missing Trooping the Colour royal engagement", 
"‘Rich people problems’: Double Bay Ferrari owner roasted over parking fail", 
"Anthony Albanese says Peter Dutton ‘worse than Scott Morrison’ on climate", 
"‘Scott was wrong!’: Perth family using EV to tow camper around Australia in first all-electric ‘big lap’", 
"National retail chain Johnny’s Furniture collapses", 
"Art Money on brink of collapse as $100m Aussie fintech pauses operations", 
"Star criticised for bizarre baby name", 
"Dr Michael Mosley’s body found in Greece, health guru ‘nearly made it’ to safety", 
"Gaza journalist who wrote for Al Jazeera was holding three hostages in home with family, Israel says", 
"Peter Costello resigns as Nine Entertainment chairman", 
"Peter Costello has resigned as Nine chair after airport clash", 
"Indigenous musician claims she was ‘refused taxis’ at airport", 
"Shoppers blast temporary staircases at Sydney Westfield", 
"Israeli commander Arnon Zamora killed in daring raid in Gaza that brought four hostages home", 
"Crushing Harry and Meghan photograph resurfaces", 
"Shark Tank judge scammed 100 times", 
"iPhones made before a certain date are now ‘vulnerable’ to cybersecurity attacks", 
"‘Gut punch’: Spotlight accused of copying small business Craft Club’s bestseller", 
"NATO preparing for potential ground war with Russia — including plans for US troop involvement", 
"Mike Tyson and Jake Paul new fight date set after legend’s health scare", 
"Toddler who was allegedly refused blood test dies in hospital", 
"Dick Van Dyke, 98, spotted with his rarely-seen wife, 52 ahead of his birthday", 
"SPC: Aussie company slashes orders for peaches and pears by 40 per cent", 
"Only 20 doctors sign up to government’s $24 million Medical Costs Finder website", 
"Probe into cancer cluster after council workers five diagnosed", 
"Big change coming to Google Maps", 
"Huge search for missing TV doctor Michael Mosley in Greece", 
"Alfred Hospital data shows men get burned by petrol more often on long weekends", 
"Dad’s shock move at daughter’s graduation", 
"‘Highly contagious’ new STD on the rise as first case reported in US", 
"Aussie pop stars’ totally naked new music video", 
"New Suri Cruise photos emerge after telling last name move", 
"Model drops 22kg in epic weight loss transformation", 
"Chinese EV brand BYD reports record sales", 
"Fed-up NSW doctor blasts Aussie bosses over sick day policy", 
"Elon Musk: eSafety commissioner drops court case against X over Sydney church stabbing", 
"MediSecure collapses into administration and liquidation after cyber ransom attack", 
"Remote Amazon tribe finally connects to internet — only to wind up hooked on porn, social media", 
"Covid vaccines may have contributed to rise in excess deaths, researchers suggest", 
"Hey Hey It’s Saturday star John Blackman dead at 76", 
"Tesla ‘graveyard’ as unsold cars pile up", 
"Dad punches comedian onstage after joke about three-month-old son", 
"Horror outcome after retailer’s $45m collapse", 
"Iconic Melbourne pub closes due to soaring costs", 
"Toyota, Honda, Mazda and Suzuki fall foul of officials over falsifying data", 
"Yoga teachers on draft core skills list above some tradies"

]

